// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lazy_crossprod_vec
arma::vec lazy_crossprod_vec(arma::mat x, arma::vec s, arma::vec c, arma::vec y);
RcppExport SEXP _lazymatrix_lazy_crossprod_vec(SEXP xSEXP, SEXP sSEXP, SEXP cSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lazy_crossprod_vec(x, s, c, y));
    return rcpp_result_gen;
END_RCPP
}
// lazy_crossprod_vec_sp
arma::vec lazy_crossprod_vec_sp(arma::sp_mat x, arma::vec s, arma::vec c, arma::vec y);
RcppExport SEXP _lazymatrix_lazy_crossprod_vec_sp(SEXP xSEXP, SEXP sSEXP, SEXP cSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lazy_crossprod_vec_sp(x, s, c, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lazymatrix_lazy_crossprod_vec", (DL_FUNC) &_lazymatrix_lazy_crossprod_vec, 4},
    {"_lazymatrix_lazy_crossprod_vec_sp", (DL_FUNC) &_lazymatrix_lazy_crossprod_vec_sp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lazymatrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
