# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast crossprod for LazyMatrix (dense case)
#' @param x Dense matrix
#' @param s Column scale inverse vector (1 / col_scales)
#' @param c Column location vector (col_locations)
#' @param y Vector to multiply
#' @return Vector result of t(X_tilde) * y
lazy_crossprod_vec <- function(x, s, c, y) {
    .Call(`_lazymatrix_lazy_crossprod_vec`, x, s, c, y)
}

#' Fast crossprod for LazyMatrix (sparse case)
#' @param x Sparse matrix (dgCMatrix)
#' @param s Column scale inverse vector (1 / col_scales)
#' @param c Column location vector (col_locations)
#' @param y Vector to multiply
#' @return Vector result of t(X_tilde) * y
lazy_crossprod_vec_sp <- function(x, s, c, y) {
    .Call(`_lazymatrix_lazy_crossprod_vec_sp`, x, s, c, y)
}

