# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lazy_crossprod_vec <- function(x, s, c, y) {
    .Call(`_lazymatrix_lazy_crossprod_vec`, x, s, c, y)
}

lazy_crossprod_vec_sp <- function(x, s, c, y) {
    .Call(`_lazymatrix_lazy_crossprod_vec_sp`, x, s, c, y)
}

